name: flutter_msa_sdk
description: MSA SDK for Flutter. You can use this plugin
  to get OAID on Android device.
version: 3.1.0
homepage: https://github.com/fjteam/flutter_msa_sdk

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.adtalos.flutter.msa.sdk
        pluginClass: FlutterMsaSdkPlugin

